/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "gpio_driver_stm32f407disc.h"
#include"LED_BUTTON.h"
int main(void)
{
	LED_INIT();
	BUTTON_INIT();

    // === Main Loop ===
    while (1)
    {
    	if(BUTTON1 == PRESSED)
    	{
    		LED1_ON;
    		smalldelay();
    		LED1_OFF;
    	}
    	else if(BUTTON2 == PRESSED)
    	{
    		LED2_ON;
    		smalldelay();
    		LED2_OFF;
    	 }
    	 else if(BUTTON3 == PRESSED)
    	 {
    		 LED3_ON;
    		 smalldelay();
    		 LED3_OFF;
    	 }
    	LED1_OFF;
        LED2_OFF;
        LED3_OFF;

    }
}
